### ISSUE TITLE
创建了Schedule，但是定时到了任务都是Pending

### ISSUE THREAD

**Issue by Desperadozx** [crawlab-team/crawlab#1031]
创建了Schedule，但是定时到了,任务都是Pending

![图片](https://user-images.githubusercontent.com/14068433/145004386-f75736bd-49f0-4897-a1ad-6f1fbd5a0ef9.png)

**Comment by tikazyq** [comment]
看看节点是否都满了？

**Comment by Desperadozx** [comment]
> 看看节点是否都满了？

没有喔，我都调得挺大的了，还有好多空位可以跑，手动启的话就正常

**Comment by voctenzuk** [comment]
I have the same problem. Tasks start ony on the master node, workers pending, when they start from schedule. But if i manually run the tasks, everything succeeds.

**Comment by tikazyq** [comment]
Fixed

**Comment by voctenzuk** [comment]
Still not working for me on latest build from dockerhub 27f43b40c872
For manual start, everything works fine.
I use multi-node deployment.
mongodb version 4.4.10
docker-compose.yml:
```
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_URI: "######"
    volumes:
      - "./.crawlab/master:/root/.crawlab"
    ports:
      - "8080:8080"
      - "9666:9666"
```

```
crawlab_master  | 2021/12/26 23:40:00  info cron: wake now 2021-12-26 23:40:00.004761001 +0800 CST
crawlab_master  | 2021/12/26 23:40:00  info cron: run now 2021-12-26 23:40:00.004761001 +0800 CST entry 2 next 2021-12-26 23:42:00 +0800 CST
crawlab_master  | 2021/12/26 23:40:00 error cron: panic stack ...
crawlab_master  | goroutine 5511 [running]:
crawlab_master  | github.com/robfig/cron/v3.Recover.func1.1.1(0x141aa90, 0x1b06f30)
crawlab_master  |       /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:45 +0xbd
crawlab_master  | panic(0x1081fc0, 0x1ab6cd0)
crawlab_master  |       /usr/local/go/src/runtime/panic.go:965 +0x1b9
crawlab_master  | github.com/crawlab-team/crawlab-core/models/models.(*User).GetId(0x0, 0x0, 0xc000000000)
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/models/user.go:17 +0x17
crawlab_master  | github.com/crawlab-team/crawlab-core/models/delegate.(*ModelDelegate).upsertArtifact(0xc0005f0c60, 0x1199ec0, 0xc001167440)
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/delegate/model.go:300 +0x438
crawlab_master  | github.com/crawlab-team/crawlab-core/models/delegate.(*ModelDelegate).add(0xc0005f0c60, 0x5, 0x0)
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/delegate/model.go:182 +0x10a
crawlab_master  | github.com/crawlab-team/crawlab-core/models/delegate.(*ModelDelegate).do(0xc0005f0c60, 0x11f63da, 0x3, 0x1431208, 0xc0005f0c60)
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/delegate/model.go:148 +0x94
crawlab_master  | github.com/crawlab-team/crawlab-core/models/delegate.(*ModelDelegate).Add(0xc0005f0c60, 0xc001167440, 0xc000027d70)
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/delegate/model.go:106 +0x45
crawlab_master  | github.com/crawlab-team/crawlab-core/task/scheduler.(*Service).Enqueue(0xc00037dc20, 0x143a938, 0xc001167440, 0x0, 0x0)
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/task/scheduler/service.go:61 +0x169
crawlab_master  | github.com/crawlab-team/crawlab-core/spider/admin.(*Service).scheduleTasks(0xc0006fe0c0, 0xc00014e1d8, 0xc0009a4000, 0xc00014e1d8, 0x0)
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/spider/admin/service.go:111 +0x3e2
crawlab_master  | github.com/crawlab-team/crawlab-core/spider/admin.(*Service).Schedule(0xc0006fe0c0, 0xfff5d75bc85c861, 0x9663503c, 0xc0009a4000, 0x0, 0x0)
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/spider/admin/service.go:45 +0x85
crawlab_master  | github.com/crawlab-team/crawlab-core/schedule.(*Service).schedule.func1()
crawlab_master  |       /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/schedule/service.go:235 +0x489
crawlab_master  | github.com/robfig/cron/v3.FuncJob.Run(0xc000b83700)
crawlab_master  |       /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x25
crawlab_master  | github.com/robfig/cron/v3.Recover.func1.1()
crawlab_master  |       /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:53 +0x68
crawlab_master  | github.com/robfig/cron/v3.FuncJob.Run(0xc0003654d0)
crawlab_master  |       /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x25
crawlab_master  | github.com/robfig/cron/v3.(*Cron).startJob.func1(0xc0005ee280, 0x1411fe0, 0xc0003654d0)
crawlab_master  |       /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x65
crawlab_master  | created by github.com/robfig/cron/v3.(*Cron).startJob
crawlab_master  |       /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0x73
crawlab_master  |
crawlab_master  | runtime error: invalid memory address or nil pointer dereference
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.0/trace.go:6 github.com/crawlab-team/go-trace.PrintError()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/schedule/logger.go:22 github.com/crawlab-team/crawlab-core/schedule.(*Logger).Error()
crawlab_master  | /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:50 github.com/robfig/cron/v3.Recover.func1.1.1()
crawlab_master  | /usr/local/go/src/runtime/panic.go:965 runtime.gopanic()
crawlab_master  | /usr/local/go/src/runtime/panic.go:212 runtime.panicmem()
crawlab_master  | /usr/local/go/src/runtime/signal_unix.go:734 runtime.sigpanic()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/models/user.go:17 github.com/crawlab-team/crawlab-core/models/models.(*User).GetId()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/delegate/model.go:300 github.com/crawlab-team/crawlab-core/models/delegate.(*ModelDelegate).upsertArtifact()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/delegate/model.go:182 github.com/crawlab-team/crawlab-core/models/delegate.(*ModelDelegate).add()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/delegate/model.go:148 github.com/crawlab-team/crawlab-core/models/delegate.(*ModelDelegate).do()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/models/delegate/model.go:106 github.com/crawlab-team/crawlab-core/models/delegate.(*ModelDelegate).Add()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/task/scheduler/service.go:61 github.com/crawlab-team/crawlab-core/task/scheduler.(*Service).Enqueue()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/spider/admin/service.go:111 github.com/crawlab-team/crawlab-core/spider/admin.(*Service).scheduleTasks()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/spider/admin/service.go:45 github.com/crawlab-team/crawlab-core/spider/admin.(*Service).Schedule()
crawlab_master  | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211122.1338/schedule/service.go:235 github.com/crawlab-team/crawlab-core/schedule.(*Service).schedule.func1()
crawlab_master  | /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 github.com/robfig/cron/v3.FuncJob.Run()
crawlab_master  | /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:53 github.com/robfig/cron/v3.Recover.func1.1()
crawlab_master  | /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 github.com/robfig/cron/v3.FuncJob.Run()
crawlab_master  | /go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 github.com/robfig/cron/v3.(*Cron).startJob.func1()
crawlab_master  | /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
```

**Comment by zplzpl** [comment]
I have the same problem.

**Comment by tikazyq** [comment]
@zplzpl are you using the latest image?
